laravel/app/Http/routes.php
        Route::post('/fornecedor_conta', 'AdministrativoController@fornecedor_store');

        Route::get('/conta_edita/{tipo}/{id}', 'AdministrativoController@editar_conta');
        Route::get('/conta_edita_pagar/{tipo}/{id}', 'AdministrativoController@editar_conta_pagar');
        Route::post('/conta_edita/{tipo}/{id}', 'AdministrativoController@conta_update');
        Route::get('/conta_cancela/{tipo}/{id}', 'AdminController@cancelar_conta');

        Route::get('/centrocusto', 'AdministrativoController@centrocusto');
        Route::post('/centrocusto', 'AdministrativoController@store');
        Route::get('/centrocusto_edita/{id}', 'AdministrativoController@editar_centrocusto');
        Route::post('/centrocusto_edita/{id}', 'AdministrativoController@update');
        Route::get('/centrocusto_lista', 'AdministrativoController@listar_centrocusto');

        Route::get('/cronograma_financeiro', 'AdministrativoController@cronograma_financeiro');
        Route::post('/cronograma_financeiro', 'AdministrativoController@cronograma_financeiro_post');

        Route::get('/medico_inativa/{id}', 'AdministrativoController@inativar_medico');
        Route::get('/medico_ativa/{id}', 'AdministrativoController@ativar_medico');
        Route::get('/medico', 'AdministrativoController@medico');
        Route::post('/medico', 'AdministrativoController@medico_store');
        Route::get('/medico_lista/{status}', 'AdministrativoController@listar_medico');
        Route::get('/medico_lista/{status}', 'AdministrativoController@buscar_medico');
        Route::post('/medico_edita/{id}', 'AdministrativoController@medico_update');
        Route::get('/medico_edita/{id}', 'AdministrativoController@editar_medico');

        Route::get('/relatorio_conta/{tipo}', 'RelatorioController@conta');
        Route::post('/relatorio_conta/{tipo}', 'RelatorioController@buscar_conta');


        Route::get('/contas_cronograma/{tipo}/{ano}/{mes}/{dia}/{centrocusto}', 'AdministrativoController@contas_cronograma');

        Route::get('/relatorio_venda/{tipo}', 'RelatorioController@relatorio_venda');
        Route::post('/relatorio_venda/{tipo}', 'RelatorioController@relatorio_venda_post');

        Route::get('/arquivos/', 'ArquivoController@arquivos');
        Route::post('/arquivos/', 'ArquivoController@store');
        Route::get('/arquivo_lista', 'ArquivoController@listar_arquivo');
        Route::get('/arquivo_lista', 'ArquivoController@buscar_arquivo');

        Route::get('/exame', 'MedicinaController@exame');
        Route::post('/exame', 'MedicinaController@exame_store');
        Route::get('/exame_lista', 'MedicinaController@listar_exame');
        Route::get('/exame_edita/{id}', 'MedicinaController@editar_exame');
        Route::post('/exame_edita/{id}', 'MedicinaController@update_exame');
        Route::get('/exame_delete/{id}', 'MedicinaController@exame_delete');

        Route::get('/laboratorio', 'MedicinaController@laboratorio');
        Route::post('/laboratorio', 'MedicinaController@laboratorio_store');
        Route::get('/laboratorio_lista', 'MedicinaController@listar_laboratorio');
        Route::get('/laboratorio_edita/{id}', 'MedicinaController@editar_laboratorio');
        Route::post('/laboratorio_edita/{id}', 'MedicinaController@update_laboratorio');
        Route::get('/laboratorio_delete/{id}', 'MedicinaController@laboratorio_delete');

        Route::get('/atendimento', 'MedicinaController@atendimento');
        Route::post('/atendimento', 'MedicinaController@atendimento_store');
        Route::get('/atendimento_lista', 'MedicinaController@listar_atendimento');
        Route::get('/atendimento_edita/{id}', 'MedicinaController@editar_atendimento');
        Route::post('/atendimento_edita/{id}', 'MedicinaController@update_atendimento');
        Route::get('/atendimento_cancela/{id}', 'MedicinaController@atendimento_cancela');
        Route::get('/medico_exame', 'MedicinaController@medico_exame');
        Route::get('/med_exame', 'MedicinaController@med_exame');
        Route::get('/laboratorio_exame', 'MedicinaController@laboratorio_exame');
        Route::get('/atendimento_medico', 'MedicinaController@atendimento_medico');
        Route::get('/empresa_exame', 'MedicinaController@empresa_exame');

        Route::get('/medico_exame_pdf', 'MedicinaController@medico_exame_pdf');
        Route::get('/med_exame_pdf', 'MedicinaController@med_exame_pdf');
        Route::get('/laboratorio_exame_pdf', 'MedicinaController@laboratorio_exame_pdf');
        Route::get('/atendimento_medico_pdf', 'MedicinaController@atendimento_medico_pdf');
        Route::get('/empresa_exame_pdf', 'MedicinaController@empresa_exame_pdf');

        Route::get('/aso/', 'AdministrativoController@aso');
        Route::post('/aso/', 'AdministrativoController@aso_post');
        Route::get('/pacientes_ajax/', 'AdministrativoController@pacientes_ajax');
        Route::get('/empresas_ajax/', 'AdministrativoController@empresas_ajax');
        Route::get('/medico_aso/{medico}', 'AdministrativoController@medico_aso');
        Route::get('/gerar_aso/{data}', 'AdministrativoController@aso_pdf');
        Route::get('/gerar_fichaclinica/{data}', 'AdministrativoController@ficha_pdf');
    });
});//2

Route::group(['prefix'=>'qualidade'], function(){
    Route::group(['middleware' => ['auth','qualidade']], function() {
        Route::get('/', 'AdministrativoController@index');

        Route::get('/cliente_ativa/{id}', 'ClienteController@ativar_cliente');
        Route::get('/cliente_inativa/{id}', 'ClienteController@inativar_cliente');
        Route::post('/cliente_edita/{id}', 'ClienteController@update');
        Route::post('/cliente', 'ClienteController@store');
        Route::get('/cliente', 'AdministrativoController@cliente');
        Route::get('/cliente_edita/{id}', 'AdministrativoController@editar_cliente');
        Route::get('/cliente_lista/{status}', 'AdministrativoController@listar_cliente');
        Route::get('/cliente_lista/{status}', 'AdministrativoController@buscar_cliente');

        Route::get('/user_view2', 'UserController@show2');
        Route::get('/user', 'AdministrativoController@user');
        Route::get('/user_edita/{id}', 'AdministrativoController@editar_user');
        Route::get('/user_resetarsenha/{id}', 'AdministrativoController@resetsenha');
        Route::get('/user_lista/', 'AdministrativoController@listar_user');
        Route::get('/user_lista/', 'AdministrativoController@buscar_user');
        Route::get('/user_inativa/{id}', 'UserController@inativar_user');
        Route::get('/user_ativa/{id}', 'UserController@ativar_user');

        Route::get('/tecnico', 'QualidadeController@tecnico');
        Route::get('/tecnico_lista/{status}', 'QualidadeController@listar_tecnico');
        Route::get('/tecnico_lista/{status}', 'QualidadeController@buscar_tecnico');
        Route::get('/tecnico_edita/{id}', 'QualidadeController@editar_tecnico');
        Route::post('/tecnico_edita/{id}', 'TecnicoController@update');
        Route::post('/tecnico', 'TecnicoController@store');
        Route::get('/tecnico_inativa/{id}', 'TecnicoController@inativar_tecnico');
        Route::get('/tecnico_ativa/{id}', 'TecnicoController@ativar_tecnico');


        Route::get('/servico', 'AdministrativoController@servico');
        Route::post('/servico', 'AdministrativoController@servico_store');
        Route::get('/servico_edita/{id}', 'AdministrativoController@editar_servico');
        Route::post('/servico_edita/{id}', 'AdministrativoController@update_servico');
        Route::get('/servico_lista', 'AdministrativoController@listar_servico');

        Route::get('/orcamento', 'AdministrativoController@orcamento');
        Route::post('/orcamento', 'AdministrativoController@orcamento_store');
        Route::get('/adicionar_servico', 'AdministrativoController@adicionar_servico');
        Route::get('/servico_valor/{id}', 'AdministrativoController@servico_valor');
        Route::get('/remover_servico/{serv}', 'AdministrativoController@remover_servico');
        Route::post('/servico_orcamento', 'AdministrativoController@servico_orcamento');
        Route::get('/buscar_orcamento', 'AdministrativoController@buscar_orcamento');
        Route::post('/buscar_orcamento', 'AdministrativoController@buscar_post_orcamento');
        Route::get('/adicionar_orcamento/{id}', 'AdministrativoController@adicionar_orcamento');
        Route::get('/finalizado/{id}', 'AdministrativoController@finaliza_orcamento');

        Route::get('/orcamento_edita/{id}/{edita?}', 'AdministrativoController@editar_orcamento');
        Route::post('/orcamento_edita/{id}', 'AdministrativoController@orcamento_update');

        Route::get('/email_orcamento/{orcamento}', 'AdministrativoController@email_orcamento');
        Route::post('/email_orcamento_post/{orcamento}', 'AdministrativoController@email_orcamento_post');

        Route::get('/orcamento_lista/{orcamento}', 'AdministrativoController@listar_orcamento');
        Route::get('/orcamento_lista/{orcamento}', 'AdministrativoController@buscar_listaorcamento');
        Route::get('/orcamento_convertidos_lista/{orcamento}', 'AdministrativoController@listar_convertidos');
        Route::get('/orcamento_convertidos_lista/{orcamento}', 'AdministrativoController@buscar_convertidos');
        Route::get('/orcamento_aprova/{id}', 'AdministrativoController@aprovar_orcamento');

        Route::get('/orcamento_inativa/{id}', 'AdministrativoController@inativar_orcamento');
        Route::get('/orcamento_ativa/{id}', 'AdministrativoController@ativar_orcamento');

        Route::get('/atividade', 'QualidadeController@atividade');
        Route::post('/atividade', 'QualidadeController@store');
        Route::get('/atividade_lista/{status}', 'QualidadeController@listar_atividade');
        Route::get('/atividade_edita/{id}', 'QualidadeController@editar_atividade');
        Route::post('/atividade_edita/{id}', 'QualidadeController@update');

laravel/app/Atendimento.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Menu
 * @package App\Models\Admin
 * @version September 25, 2018, 5:06 pm -03
 *
 * @property \Illuminate\Database\Eloquent\Collection clientes
 * @property \Illuminate\Database\Eloquent\Collection cursos
 * @property \Illuminate\Database\Eloquent\Collection MenuExame
 * @property \Illuminate\Database\Eloquent\Collection pagamentos
 * @property \Illuminate\Database\Eloquent\Collection videos
 * @property string nome
 * @property integer drop
 * @property integer ontop
 * @property integer onfooter
 * @property integer ordem
 */
class Atendimento extends Model
{

    public $table = 'atendimentos';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';




    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/

    public function atendimentoExames()
    {
        return $this->hasMany(\App\AtendimentoExame::class, 'atendimento_id');
    }

    public function statu()
    {
        return $this->belongsTo(\App\Statu::class, 'statu_id');
    }

    public function paciente()
    {
        return $this->belongsTo(\App\Paciente::class, 'paciente_id');
    }

    public function medico()
    {
        return $this->belongsTo(\App\Medico::class, 'medico_id');
    }

    public function exames()
    {
        return $this->belongsToMany(\App\Exame::class,'atendimento_exames', 'atendimento_id','exame_id');
    }

    public function status(){
        return $this->belongsTo('App\Statu', 'statu_id');
    }

    public function getDataAttribute($data){
        $data = explode('-', $data);
        $ano = $data[0];
        $dia = $data[2];

        $meses = array('01' => 'Janeiro', '02' => 'Fevereiro', '03' => 'Março', '04' => 'Abril', '05' => 'Maio', '06' => 'Junho', '07' => 'Julho', '08' => 'Agosto', '09' => 'Setembro', '10' => 'Outubro', '11' => 'Novembro', '12' => 'Dezembro');

        $mes = $meses[$data[1]];
        $dataformatada = $dia.' '.$mes.', '.$ano;

        return $dataformatada;
    }

    public function getValorRAttribute()
    {
        return "R$ ".number_format($this->valor, 2, ",", ".");
    }

    public function getValorMedAttribute()
    {
        return "R$ ".number_format($this->valor_medico, 2, ",", ".");
    }



}

laravel/resources/views/atendimento/atendimentos.blade.php
@extends('app')
@section('title', 'Listar Atendimentos')
@section('content')

    <script type="text/javascript" src="/js/validador/delete.js"></script>
    <div class="container">
        <div class="row  bg">
            <div class="col s12 bgverde">
                <p class="bold font20 corbranca">Lista de Atendimentos</p>
            </div>
        </div>

        <div class="row buscar">
            {!! Form::open(['class' => 'col s12', 'method' => 'GET']) !!}
            <div class="row">

                <a href="{{ Route::getCurrentRoute()->getPrefix() }}/atendimento_lista" class="waves-effect waves-light btn">Limpar</a>
                <button class="btn waves-effect waves-light" type="submit">
                    <i class="material-icons right">search</i>
                </button>
                <div class="input-field col m2 s3">
                    {!! Form::label('fim', 'Data final: ') !!}
                    {!! Form::text('fim', (isset($data['fim']) ? $data['fim']:''), ['class' => 'datepicker picker__input', 'id' => 'fim', 'tabindex' => -1, 'aria-expanded' => 'false', 'aria-readonly' => 'false', 'aria-haspopup' => 'true', 'readonly' => '']) !!}
                </div>
                <div class="input-field col m2 s3">
                    {!! Form::label('inicio', 'Data inicial: ') !!}
                    {!! Form::text('inicio', (isset($data['inicio']) ? $data['inicio']:''), ['class' => 'datepicker picker__input', 'id' => 'inicio', 'tabindex' => -1, 'aria-expanded' => 'false', 'aria-readonly' => 'false', 'aria-haspopup' => 'true', 'readonly' => '']) !!}
                </div>
                <div class="input-field col s3 m2">
                    {!! Form::select('statu_id', ['' => 'Todos status', '1' => 'Ativos', '3' => 'Cancelado'], isset($data['statu_id']) ? $data['statu_id'] : null, ['id' => 'status']) !!}
                </div>
            </div>
            {!! Form::close() !!}
        </div>
        <div class="row">
            <div class="col s12">
                <table class="bordered highlight">
                    <thead>
                    <tr>
                        <th>Descrição</th>
                        <th>Data</th>
                        <th>Paciente</th>
                        <th>Medico</th>
                        <th>Ações</th>
                    </tr>
                    </thead>

                    <tbody>
                    @forelse($atendimentos as $atendimento)
                        <tr>
                            <td>{{ $atendimento->descricao }}</td>
                            <td>{{ $atendimento->data }}</td>
                            <td>{{ $atendimento->paciente->nome }}</td>
                            <td>{{ $atendimento->medico->nome }}</td>
                            <td>
                                <div class="fixed-action-btn horizontal">
                                    <a class="btn-floating btn-sm green">
                                        <i class="large mdi-navigation-menu"></i>
                                    </a>
                                    <ul class="opcoes">
                                        <li><a href="{{ Route::getCurrentRoute()->getPrefix() }}/atendimento_edita/{{ base64_encode($atendimento->id) }}" title="Editar atendimento" class="btn-floating blue darken-1"><i class="material-icons">description</i></a></li>

                                            <li><a href="#" data-href="{{ Route::getCurrentRoute()->getPrefix() }}/atendimento_cancela/{{ base64_encode($atendimento->id) }}" data-text="Tem certeza que deseja excluir este atendimento?" title="Excluir atendimento" class="btn-floating red delete"><i class="fa fa-times"></i></a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                        @if($atendimento->statu_id != 3)
                        <tr>
                            <td colspan="6">
                                <table>
                                    <span class="font-weight-bold">Exames</span><br>
                                    @foreach($atendimento->atendimentoExames as $exame)
                                        <tr>
                                            <td class="p-0"> {{$exame->exame->nome}}</td>
                                            <td class="p-0">   {{$exame->laboratorio->nome}} </td>
                                            <td class="p-0">   <span class="font-weight-bold">Valor: </span>{{$exame->valor_r}}</td>
                                            <td class="p-0">   <span class="font-weight-bold">Valor Médico: </span>{{$exame->valor_med}}</td>
                                        </tr>
                                    @endforeach
                                </table>
                            </td>
                        </tr>
                        @endif
                    @empty
                        <tr>
                            <td colspan="6">Nenhum atendimento encontrado.</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            <div class="col s12 paginacao"><?php echo $atendimentos->appends(Request::all())->render(); ?></div>
        </div>
    </div>
    <div id="modal1" class="modal"></div>
@endsection

laravel/resources/views/atendimento/empresa_exame.blade.php
@extends('app')
@section('title', 'Listar Atendimentos')
@section('content')

    <link href="/css/select2-materialize.css" rel="stylesheet" />
    <script src="/js/jquery-ui.min.js"></script>
    <script src="/js/select2.full.min.js"></script>
    <script src="/js/i18n/pt-BR.js" type="text/javascript"></script>
    <script src="/js/select2-materialize.js"></script>

    <script type="text/javascript" src="/js/validador/relatorio_cliente.js"></script>
    <script type="text/javascript" src="/js/validador/delete.js"></script>
    <div class="container">
        <div class="row  bg">
            <div class="col s12 bgverde">
                <p class="bold font20 corbranca">Relatório de exame por Empresa</p>
            </div>
        </div>

        <div class="row buscar">
            {!! Form::open(['class' => 'col s12', 'method' => 'GET']) !!}
            <input type="hidden" id="prefixo" value="{{ Route::getCurrentRoute()->getPrefix() }}">
            <div class="row">

                <a href="{{ Route::getCurrentRoute()->getPrefix() }}/empresa_exame" class="waves-effect waves-light btn">Limpar</a>
                <button class="btn waves-effect waves-light" type="submit" id="Envia">
                    <i class="material-icons right">search</i>
                </button>
                <div class="input-field col m2 s12">
                    {!! Form::label('fim', 'Data final: ') !!}
                    {!! Form::text('fim', (isset($data['fim']) ? $data['fim']:''), ['class' => 'datepicker picker__input', 'id' => 'fim', 'tabindex' => -1, 'aria-expanded' => 'false', 'aria-readonly' => 'false', 'aria-haspopup' => 'true', 'readonly' => '']) !!}
                </div>
                <div class="input-field col m2 s12">
                    {!! Form::label('inicio', 'Data inicial: ') !!}
                    {!! Form::text('inicio', (isset($data['inicio']) ? $data['inicio']:''), ['class' => 'datepicker picker__input', 'id' => 'inicio', 'tabindex' => -1, 'aria-expanded' => 'false', 'aria-readonly' => 'false', 'aria-haspopup' => 'true', 'readonly' => '']) !!}
                </div>

                <div class="input-field col s12 m6  text-left">
                    <select name="empresa_id" id="empresa_id">
                        <option value="">Selecione</option>
                    </select>
                    {!! Form::label('empresa_id', 'Empresa: ' ,array('class' => 'paciente_select')) !!}
                </div>

            </div>
            {!! Form::close() !!}
        </div>

        @if(isset($atendimentos))
            <div class="row">
                <div class="col s12 text-right">
                    <a href="{{ Route::getCurrentRoute()->getPrefix() }}/empresa_exame_pdf?{{(http_build_query(Request::all()))}}" target="_blank" class="waves-effect waves-light btn btn-lh"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> Gerar PDF</a>
                </div>
                <div class="col s12">
                    <table class="bordered highlight">
                        <thead>
                        <tr>
                            <th>Data</th>
                            <th>Funcionário/Paciente</th>
                            <th colspan="2">Exame</th>
                            <th>Valor</th>
                            {{--<th>Valor Médico</th>--}}
                        </tr>
                        </thead>

                        <tbody>
                        @forelse($atendimentos as $atendimento)
                            <tr>
                                <td>{{ $atendimento->data }}</td>
                                <td>{{ $atendimento->nome }}<br>
                                    <small>{{ $atendimento->funcao }}</small>
                                </td>
                                <td>{{ $atendimento->descricao }}</td>
                                <td>{{ $atendimento->exame }}</td>
                                <td>{{ $atendimento->valor_r }}</td>
                                {{--<td>{{ $atendimento->valor_med }}</td>--}}
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5">Nenhum exame encontrado.</td>
                            </tr>
                        @endforelse

                        @if(sizeof($atendimentos)>0)
                            <tr>
                                <td></td>
                                <td class="text-center font-weight-bold"><strong>Total</strong></td>
                                <td></td>
                                <td></td>
                                <td class="font-weight-bold">Valor Exame total</td>
                                {{--<td class="font-weight-bold">Valor Médico total</td>--}}
                            </tr>
                            <tr>
                                <td></td>
                                <td class="text-center">{{sizeof($atendimentos)}}</td>
                                <td></td>
                                <td></td>
                                <td>{{$valor_total}}</td>
                                {{--<td>{{$valor_medico_total}}</td>--}}
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        @endif
    </div>
    <div id="modal1" class="modal"></div>

    <script>
        $(document).ready(function() {
            $('#empresa_id').select2({
                language: "pt-BR",
                minimumInputLength: 5,
                ajax: {
                    url: $('#prefixo').val()+'/empresas_ajax',
                    dataType: 'json',
                    data: function(params) {
                        return {
                            term: params.term || '',
                            page: params.page || 1
                        }
                    },
                    cache: true
                }
            });

            @if(!empty($cliente))
                var data = {
                    id: {{$cliente['id']}},
                    text: '{{$cliente['nome']}} - {{$cliente['cnpj']}}'
                };

                var newOption = new Option(data.text, data.id, false, false);
                $('#empresa_id').append(newOption).trigger('change');

                $('#empresa_id').val('{{$cliente['id']}}').trigger('change');

            @endif

        });
    </script>
@endsection

laravel/resources/views/atendimento/laboratorio_exame.blade.php
@extends('app')
@section('title', 'Listar Atendimentos')
@section('content')

    <script type="text/javascript" src="/js/validador/relatorio_laboratorio.js"></script>
    <script type="text/javascript" src="/js/validador/delete.js"></script>
    <div class="container">
        <div class="row  bg">
            <div class="col s12 bgverde">
                <p class="bold font20 corbranca">Relatório de exame por Laboratório</p>
            </div>
        </div>

        <div class="row buscar">
            {!! Form::open(['class' => 'col s12', 'method' => 'GET']) !!}
            <div class="row">

                <a href="{{ Route::getCurrentRoute()->getPrefix() }}/laboratorio_exame" class="waves-effect waves-light btn">Limpar</a>
                <button class="btn waves-effect waves-light" type="submit" id="Envia">
                    <i class="material-icons right">search</i>
                </button>
                <div class="input-field col m2 s3">
                    {!! Form::label('fim', 'Data final: ') !!}
                    {!! Form::text('fim', (isset($data['fim']) ? $data['fim']:''), ['class' => 'datepicker picker__input', 'id' => 'fim', 'tabindex' => -1, 'aria-expanded' => 'false', 'aria-readonly' => 'false', 'aria-haspopup' => 'true', 'readonly' => '']) !!}
                </div>
                <div class="input-field col m2 s3">
                    {!! Form::label('inicio', 'Data inicial: ') !!}
                    {!! Form::text('inicio', (isset($data['inicio']) ? $data['inicio']:''), ['class' => 'datepicker picker__input', 'id' => 'inicio', 'tabindex' => -1, 'aria-expanded' => 'false', 'aria-readonly' => 'false', 'aria-haspopup' => 'true', 'readonly' => '']) !!}
                </div>
                <div class="input-field col s4 m3">
                    {!! Form::select('laboratorio_id', ['' => 'Selecione o laboratório']+$laboratorios, isset($data['laboratorio_id']) ? $data['laboratorio_id'] : null, ['id' => 'laboratorios']) !!}
                </div>
            </div>
            {!! Form::close() !!}
        </div>

        @if(isset($atendimentos))
            <div class="row">
                <div class="col s12 text-right">
                    <a href="{{ Route::getCurrentRoute()->getPrefix() }}/laboratorio_exame_pdf?{{(http_build_query(Request::all()))}}" target="_blank" class="waves-effect waves-light btn btn-lh"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> Gerar PDF</a>
                </div>
                <div class="col s12">
                    <table class="bordered highlight">
                        <thead>
                        <tr>
                            <th class="small-th">Nº de exames</th>
                            <th>Exame</th>
                            <th>Paciente</th>
                            <th>Valor Exame</th>
                            <th>Valor Médico</th>
                        </tr>
                        </thead>

                        <tbody>
                        @forelse($atendimentos as $atendimento)
                            <tr>
                                <td class="text-center">1</td>
                                <td>{{ $atendimento->exame }}</td>
                                <td>{{ $atendimento->nome }}</td>
                                <td>{{ $atendimento->valor_r }}</td>
                                <td>{{ $atendimento->valor_med }}</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5">Nenhum exame encontrado.</td>
                            </tr>
                        @endforelse

                        @if(sizeof($atendimentos)>0)
                            <tr>
                                <td class="text-center font-weight-bold">Total</td>
                                <td></td>
                                <td></td>
                                <td class="font-weight-bold">Valor Exame total</td>
                                <td class="font-weight-bold">Valor Médico total</td>
                            </tr>
                            <tr>
                                <td class="text-center">{{sizeof($atendimentos)}}</td>
                                <td></td>
                                <td></td>
                                <td>{{$valor_total}}</td>
                                <td>{{$valor_medico_total}}</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        @endif
    </div>
    <div id="modal1" class="modal"></div>
@endsection