laravel/app/Http/routes.php
        Route::post('/medico', 'AdministrativoController@medico_store');
        Route::get('/medico_lista/{status}', 'AdministrativoController@listar_medico');
        Route::get('/medico_lista/{status}', 'AdministrativoController@buscar_medico');
        Route::post('/medico_edita/{id}', 'AdministrativoController@medico_update');
        Route::get('/medico_edita/{id}', 'AdministrativoController@editar_medico');

        Route::get('/relatorio_conta/{tipo}', 'RelatorioController@conta');
        Route::post('/relatorio_conta/{tipo}', 'RelatorioController@buscar_conta');


        Route::get('/contas_cronograma/{tipo}/{ano}/{mes}/{dia}/{centrocusto}', 'AdministrativoController@contas_cronograma');

        Route::get('/relatorio_venda/{tipo}', 'RelatorioController@relatorio_venda');
        Route::post('/relatorio_venda/{tipo}', 'RelatorioController@relatorio_venda_post');

        Route::get('/arquivos/', 'ArquivoController@arquivos');
        Route::post('/arquivos/', 'ArquivoController@store');
        Route::get('/arquivo_lista', 'ArquivoController@listar_arquivo');
        Route::get('/arquivo_lista', 'ArquivoController@buscar_arquivo');

        Route::get('/exame', 'MedicinaController@exame');
        Route::post('/exame', 'MedicinaController@exame_store');
        Route::get('/exame_lista', 'MedicinaController@listar_exame');
        Route::get('/exame_edita/{id}', 'MedicinaController@editar_exame');
        Route::post('/exame_edita/{id}', 'MedicinaController@update_exame');
        Route::get('/exame_delete/{id}', 'MedicinaController@exame_delete');

        Route::get('/laboratorio', 'MedicinaController@laboratorio');
        Route::post('/laboratorio', 'MedicinaController@laboratorio_store');
        Route::get('/laboratorio_lista', 'MedicinaController@listar_laboratorio');
        Route::get('/laboratorio_edita/{id}', 'MedicinaController@editar_laboratorio');
        Route::post('/laboratorio_edita/{id}', 'MedicinaController@update_laboratorio');
        Route::get('/laboratorio_delete/{id}', 'MedicinaController@laboratorio_delete');

        Route::get('/atendimento', 'MedicinaController@atendimento');
        Route::post('/atendimento', 'MedicinaController@atendimento_store');
        Route::get('/atendimento_lista', 'MedicinaController@listar_atendimento');
        Route::get('/atendimento_edita/{id}', 'MedicinaController@editar_atendimento');
        Route::post('/atendimento_edita/{id}', 'MedicinaController@update_atendimento');
        Route::get('/atendimento_cancela/{id}', 'MedicinaController@atendimento_cancela');
        Route::get('/medico_exame', 'MedicinaController@medico_exame');
        Route::get('/med_exame', 'MedicinaController@med_exame');
        Route::get('/laboratorio_exame', 'MedicinaController@laboratorio_exame');
        Route::get('/atendimento_medico', 'MedicinaController@atendimento_medico');
        Route::get('/empresa_exame', 'MedicinaController@empresa_exame');

        Route::get('/medico_exame_pdf', 'MedicinaController@medico_exame_pdf');
        Route::get('/med_exame_pdf', 'MedicinaController@med_exame_pdf');
        Route::get('/laboratorio_exame_pdf', 'MedicinaController@laboratorio_exame_pdf');
        Route::get('/atendimento_medico_pdf', 'MedicinaController@atendimento_medico_pdf');
        Route::get('/empresa_exame_pdf', 'MedicinaController@empresa_exame_pdf');

        Route::get('/aso/', 'AdministrativoController@aso');
        Route::post('/aso/', 'AdministrativoController@aso_post');
        Route::get('/pacientes_ajax/', 'AdministrativoController@pacientes_ajax');
        Route::get('/empresas_ajax/', 'AdministrativoController@empresas_ajax');
        Route::get('/medico_aso/{medico}', 'AdministrativoController@medico_aso');
        Route::get('/gerar_aso/{data}', 'AdministrativoController@aso_pdf');
        Route::get('/gerar_fichaclinica/{data}', 'AdministrativoController@ficha_pdf');
    });
});//2

Route::group(['prefix'=>'qualidade'], function(){
    Route::group(['middleware' => ['auth','qualidade']], function() {
        Route::get('/', 'AdministrativoController@index');

        Route::get('/cliente_ativa/{id}', 'ClienteController@ativar_cliente');
        Route::get('/cliente_inativa/{id}', 'ClienteController@inativar_cliente');
        Route::post('/cliente_edita/{id}', 'ClienteController@update');
        Route::post('/cliente', 'ClienteController@store');
        Route::get('/cliente', 'AdministrativoController@cliente');
        Route::get('/cliente_edita/{id}', 'AdministrativoController@editar_cliente');
        Route::get('/cliente_lista/{status}', 'AdministrativoController@listar_cliente');
        Route::get('/cliente_lista/{status}', 'AdministrativoController@buscar_cliente');

        Route::get('/user_view2', 'UserController@show2');
        Route::get('/user', 'AdministrativoController@user');
        Route::get('/user_edita/{id}', 'AdministrativoController@editar_user');
        Route::get('/user_resetarsenha/{id}', 'AdministrativoController@resetsenha');
        Route::get('/user_lista/', 'AdministrativoController@listar_user');
        Route::get('/user_lista/', 'AdministrativoController@buscar_user');
        Route::get('/user_inativa/{id}', 'UserController@inativar_user');
        Route::get('/user_ativa/{id}', 'UserController@ativar_user');

        Route::get('/tecnico', 'QualidadeController@tecnico');
        Route::get('/tecnico_lista/{status}', 'QualidadeController@listar_tecnico');
        Route::get('/tecnico_lista/{status}', 'QualidadeController@buscar_tecnico');
        Route::get('/tecnico_edita/{id}', 'QualidadeController@editar_tecnico');
        Route::post('/tecnico_edita/{id}', 'TecnicoController@update');
        Route::post('/tecnico', 'TecnicoController@store');
        Route::get('/tecnico_inativa/{id}', 'TecnicoController@inativar_tecnico');
        Route::get('/tecnico_ativa/{id}', 'TecnicoController@ativar_tecnico');


        Route::get('/servico', 'AdministrativoController@servico');
        Route::post('/servico', 'AdministrativoController@servico_store');
        Route::get('/servico_edita/{id}', 'AdministrativoController@editar_servico');
        Route::post('/servico_edita/{id}', 'AdministrativoController@update_servico');
        Route::get('/servico_lista', 'AdministrativoController@listar_servico');

        Route::get('/orcamento', 'AdministrativoController@orcamento');
        Route::post('/orcamento', 'AdministrativoController@orcamento_store');
        Route::get('/adicionar_servico', 'AdministrativoController@adicionar_servico');
        Route::get('/servico_valor/{id}', 'AdministrativoController@servico_valor');
        Route::get('/remover_servico/{serv}', 'AdministrativoController@remover_servico');
        Route::post('/servico_orcamento', 'AdministrativoController@servico_orcamento');
        Route::get('/buscar_orcamento', 'AdministrativoController@buscar_orcamento');
        Route::post('/buscar_orcamento', 'AdministrativoController@buscar_post_orcamento');
        Route::get('/adicionar_orcamento/{id}', 'AdministrativoController@adicionar_orcamento');
        Route::get('/finalizado/{id}', 'AdministrativoController@finaliza_orcamento');

        Route::get('/orcamento_edita/{id}/{edita?}', 'AdministrativoController@editar_orcamento');
        Route::post('/orcamento_edita/{id}', 'AdministrativoController@orcamento_update');

        Route::get('/email_orcamento/{orcamento}', 'AdministrativoController@email_orcamento');
        Route::post('/email_orcamento_post/{orcamento}', 'AdministrativoController@email_orcamento_post');

        Route::get('/orcamento_lista/{orcamento}', 'AdministrativoController@listar_orcamento');
        Route::get('/orcamento_lista/{orcamento}', 'AdministrativoController@buscar_listaorcamento');
        Route::get('/orcamento_convertidos_lista/{orcamento}', 'AdministrativoController@listar_convertidos');
        Route::get('/orcamento_convertidos_lista/{orcamento}', 'AdministrativoController@buscar_convertidos');
        Route::get('/orcamento_aprova/{id}', 'AdministrativoController@aprovar_orcamento');

        Route::get('/orcamento_inativa/{id}', 'AdministrativoController@inativar_orcamento');
        Route::get('/orcamento_ativa/{id}', 'AdministrativoController@ativar_orcamento');

        Route::get('/atividade', 'QualidadeController@atividade');
        Route::post('/atividade', 'QualidadeController@store');
        Route::get('/atividade_lista/{status}', 'QualidadeController@listar_atividade');
        Route::get('/atividade_edita/{id}', 'QualidadeController@editar_atividade');
        Route::post('/atividade_edita/{id}', 'QualidadeController@update');
        Route::get('/atividade_inativa/{id}', 'QualidadeController@inativar_atividade');
        Route::get('/atividade_ativa/{id}', 'QualidadeController@ativar_atividade');

        Route::get('/remover_servico_edit/{orcamento}/{serv}', 'AdministrativoController@remover_servico_edit');

        Route::get('/cronograma', 'AdministrativoController@cronograma');
        Route::post('/cronograma', 'AdministrativoController@cronograma_post');
        Route::get('/buscar_cliente_cronograma', 'AdministrativoController@buscar_cliente_cronograma');
        Route::post('/buscar_cliente_cronograma', 'AdministrativoController@buscar_post_cliente_cronograma');
        Route::get('/adicionar_cronograma/{id}', 'AdministrativoController@adicionar_cronograma');
        Route::get('/adicionar_atividade/{cliente}/{tecnico}/{atividade}/{ano}/{mes}', 'AdministrativoController@adicionar_atividade_cronograma');
        Route::post('/adicionar_atividade/{cliente}/{tecnico}/{atividade}/{ano}/{mes}', 'AdministrativoController@adicionar_atividade_cronograma_post');
        Route::post('/cronograma_edita_post/{id}', 'AdministrativoController@editar_cronograma_post');
        Route::get('/cronograma_edita/{id}', 'AdministrativoController@editar_cronograma');

laravel/app/Aso.php
<?php namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Aso extends Model {

    protected $table = 'asos';


    public function paciente(){
        return $this->belongsTo('App\Paciente', 'paciente_id');
    }
    public function medico(){
        return $this->belongsTo('App\Medico', 'medico_id');
    }

    public function getCreatedAtAttribute($date){
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y');
    }

}

laravel/resources/views/aso/aso.blade.php
@extends('app')
@section('title', 'Listar Arquivos')
@section('content')



    <div class="container">
        <div class="row  bg">
            <div class="col s12 bgverde">
                <p class="bold font20 corbranca">Lista de arquivos</p>
            </div>
        </div>
        <div class="row buscar">
            {!! Form::open(['class' => 'col s12', 'method' => 'GET']) !!}
            <div class="row">
                <a href="{{ Route::getCurrentRoute()->getPrefix() }}/arquivo_lista" class="waves-effect waves-light btn">Limpar</a>
                <button class="btn waves-effect waves-light" type="submit" name="action">
                    <i class="material-icons right">search</i>
                </button>

                <div class="input-field col m2 s3">

                    {!! Form::label('fim', 'Data final: ') !!}
                    {!! Form::text('fim', (isset($data['fim']) ? $data['fim']:''), ['class' => 'datepicker picker__input', 'id' => 'fim', 'tabindex' => -1, 'aria-expanded' => 'false', 'aria-readonly' => 'false', 'aria-haspopup' => 'true', 'readonly' => '']) !!}
                </div>
                <div class="input-field col m2 s3">
                    {!! Form::label('inicio', 'Data inicial: ') !!}
                    {!! Form::text('inicio', (isset($data['inicio']) ? $data['inicio']:''), ['class' => 'datepicker picker__input', 'id' => 'inicio', 'tabindex' => -1, 'aria-expanded' => 'false', 'aria-readonly' => 'false', 'aria-haspopup' => 'true', 'readonly' => '']) !!}
                </div>

                <div class="input-field col m2 s3">
                    {!! Form::text('arquivo', (isset($data['arquivo']) ? $data['arquivo']:''), ['class'=>'validate', 'placeholder'=>'Por Nome']) !!}
                </div>

            </div>
            {!! Form::close() !!}
        </div>

        <div class="row">
            <div class="col s12">
                <table class="bordered highlight">
                    <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Clientes</th>
                        <th>Arquivo</th>
                        <th>Data</th>
                        <th>Ações</th>
                    </tr>
                    </thead>

                    <tbody>
                    @forelse($arquivos as $arquivo)

                        <tr>
                            <td>{{ $arquivo->nome }}</td>
                            <td>{!! $arquivo->clientes !!}</td>
                            <td>{{ $arquivo->file }}</td>
                            <td>{{ $arquivo->created_at }}</td>
                            <td>
                                <div class="fixed-action-btn horizontal">
                                    <a class="btn-floating btn-sm green">
                                        <i class="large mdi-navigation-menu"></i>
                                    </a>
                                    <ul class="opcoes">
                                        <li><a href="/uploads/arquivo/{{$arquivo->file}}" target="_blank" title="Visualizar Arquivo" class="btn-floating yellow"><i class="material-icons">visibility</i></a></li>
                                        @if((Auth::user()->role_id == 6) || (Auth::user()->role_id == 7) || (Auth::user()->role_id == 1))
                                            @if($arquivo->statu_id != 3)
                                                <li><a href="{{ Route::getCurrentRoute()->getPrefix() }}/cancelar_arquivo/{{ base64_encode($arquivo->id) }}" title="Cancelar arquivo" class="iframe btn-floating red"><i class="fa fa-times"></i></a></li>
                                            @endif
                                        @endif

                                    </ul>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5">Nenhum Arquivo encontrado.</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            <div class="col s12 paginacao">
                <?php echo $arquivos->appends(Request::all())->render(); ?>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/aso/aso_add.blade.php
@extends('app')
@section('title', 'Cadastrar Arquivo')
@section('content')


    <link href="/css/select2-materialize.css" rel="stylesheet" />
    <script src="/js/jquery-ui.min.js"></script>
    <script src="/js/select2.full.min.js"></script>
    <script src="/js/i18n/pt-BR.js" type="text/javascript"></script>
    <script src="/js/select2-materialize.js"></script>
    <script type="text/javascript" src="/js/validador/aso.js"></script>

    <script>

    </script>

    <div class="container">
        <div class="row  bg">
            <div class="col s12 bgverde">
                <p class="bold font20 corbranca">Cadastro de ASO</p>
            </div>
        </div>
        <div class="row">

            {!! Form::open(['class' => 'col s12','id' => 'asoform' ,'files' => 'true']) !!}
            <input type="hidden" id="prefixo" value="{{ Route::getCurrentRoute()->getPrefix() }}">

            <div class="row padding">


                <div class="input-field col m6 s12">
                    <select name="medico" id="medico">
                        <option value="">Selecione</option>
                        @foreach($medicos as $key => $medico)
                        <option value="{{$key}}">{{$medico}}</option>
                        @endforeach
                    </select>
                    {!! Form::label('medico', '*  Médico: ') !!}
                </div>


                <div class="input-field col m6 s12">
                    <select name="paciente" id="paciente">
                        <option value="">Selecione</option>
                    </select>
                    {!! Form::label('pacicente', '*  Paciente: ' ,array('class' => 'paciente_select')) !!}
                </div>

                <div class="input-field col m2 s4">
                    {!! Form::text('valor','', ['class' => 'validate', 'id' => 'valor']) !!}
                    {!! Form::label('valor', '* Valor: ') !!}
                </div>

            </div>


            <div class="row right-align">
                <button class="btn waves-effect waves-light" type="submit" id="Envia" name="action">Cadastrar <i class="material-icons right">send</i>
                </button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
    <div id="modal1" class="modal"></div>

    <script>
        $(document).ready(function() {
            $('#paciente').select2({
                language: "pt-BR",
                minimumInputLength: 5,

                ajax: {
                    url: $('#prefixo').val()+'/pacientes_ajax',
                    dataType: 'json',
                    data: function(params) {
                        return {
                            term: params.term || '',
                            page: params.page || 1
                        }
                    },
                    cache: true
                }
            });


        });
    </script>
@endsection

laravel/resources/views/aso/medico_aso.blade.php
@extends('app')
@section('title', 'Listar Orçamentos')
@section('content')


    <div class="container">
        <div class="row  bg">
            <div class="col s12 bgverde">
                <p class="bold font20 corbranca">Lista de ASO | Médico: {{$medico->nome}}</p>
            </div>
        </div>
        <div class="row buscar">
            {!! Form::open(['class' => 'col s12', 'method' => 'GET']) !!}
            <div class="row">
                <a href="{{ Route::getCurrentRoute()->getPrefix() }}/medico_aso/{{base64_encode($medico->id)}}" class="waves-effect waves-light btn">Limpar</a>
                <button class="btn waves-effect waves-light" type="submit" name="action">
                    <i class="material-icons right">search</i>
                </button>

                <div class="input-field col m2 s3">

                    {!! Form::label('fim', 'Data final: ') !!}
                    {!! Form::text('fim', (isset($data['fim']) ? $data['fim']:''), ['class' => 'datepicker picker__input', 'id' => 'fim', 'tabindex' => -1, 'aria-expanded' => 'false', 'aria-readonly' => 'false', 'aria-haspopup' => 'true', 'readonly' => '']) !!}
                </div>
                <div class="input-field col m2 s3">
                    {!! Form::label('inicio', 'Data inicial: ') !!}
                    {!! Form::text('inicio', (isset($data['inicio']) ? $data['inicio']:''), ['class' => 'datepicker picker__input', 'id' => 'inicio', 'tabindex' => -1, 'aria-expanded' => 'false', 'aria-readonly' => 'false', 'aria-haspopup' => 'true', 'readonly' => '']) !!}
                </div>

                @if($total != 0)
                <div class="total">Valor total: R$ {{$total}}</div>
                @endif
            </div>
            {!! Form::close() !!}
        </div>

        <div class="row">
            <div class="col s12">
                <table class="bordered highlight">
                    <thead>
                    <tr>
                        <th>Número</th>
                        <th>Paciente</th>
                        <th>Valor</th>
                        <th>Data</th>
                        <th>Ações</th>
                    </tr>
                    </thead>

                    <tbody>

                    @forelse($asos as $aso)
                        <tr>

                            <td>{{$aso->id}}</td>
                            <td>{{$aso->nome}}</td>
                            <td>{{$aso->valor}}</td>
                            <td>{{$aso->created_at}}</td>
                            <td>
                                <div class="fixed-action-btn horizontal">
                                    <a class="btn-floating btn-sm green">
                                        <i class="large mdi-navigation-menu"></i>
                                    </a>
                                    <ul class="opcoes">
                                        <li><a href="{{ Route::getCurrentRoute()->getPrefix() }}/gerar_aso/{{ base64_encode($aso->medico_id.'-'.$aso->paciente_id) }}" title="Imprimir ASO" target="_blank" class="btn-floating orange"><i class="material-icons">print</i></a></li>
                                        <li><a href="{{ Route::getCurrentRoute()->getPrefix() }}/gerar_fichaclinica/{{ base64_encode($aso->medico_id.'-'.$aso->paciente_id) }}" title="Imprimir Ficha clinica" target="_blank" class="btn-floating blue "><i class="material-icons">print</i></a></li>

                                    </ul>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6">Nenhum ASO encontrado.</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            <div class="col s12 paginacao">
                <?php echo $asos->appends(Request::all())->render(); ?>
            </div>
        </div>
    </div>
@endsection